-- Create Database
CREATE
    DATABASE D2K_LIST_WEB;

-- User Database
USE
    D2K_LIST_WEB;

-- Create Table
-- ===== MASTER TABLE =====
-- User
CREATE TABLE `TBL_M_USER`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `FIRST_NAME`  VARCHAR(50) NOT NULL,
    `LAST_NAME`   VARCHAR(50) NOT NULL,
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL
);
-- Account
CREATE TABLE `TBL_M_ACCOUNT`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_NAME`   VARCHAR(50) NOT NULL,
    `PASSWORD`    LONGTEXT    NOT NULL,
    `USER_ID`     BIGINT,
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TBL_M_USER (ID)
);

-- Icon
CREATE TABLE `TBL_M_ICON`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME`        VARCHAR(50) NOT NULL,
    `FILE_NAME`   VARCHAR(50) NOT NULL,
    `TYPE`        VARCHAR(50) NOT NULL,
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL
);

-- Menu
CREATE TABLE `TBL_M_MENU`
(
    `ID`             BIGINT PRIMARY KEY AUTO_INCREMENT,
    `INDEX_ID`       INT         NOT NULL UNIQUE,
    `ICON`           VARCHAR(50) NOT NULL,
    `CODE`           VARCHAR(50) NOT NULL UNIQUE,
    `NAME`           VARCHAR(50) NOT NULL,
    `OBJECT_NAME`    VARCHAR(50) NOT NULL,
    `DESCRIPTION`    VARCHAR(255),
    `MENU_PARENT_ID` BIGINT,
    `PATH`           VARCHAR(50) NOT NULL,
    `CREATE_BY`      VARCHAR(50) NOT NULL,
    `CREATE_DATE`    TIMESTAMP   NOT NULL,
    `UPDATE_BY`      VARCHAR(50) NOT NULL,
    `UPDATE_DATE`    TIMESTAMP   NOT NULL
);

-- System Constant
CREATE TABLE `TBL_M_SYSTEM_CONSTANT`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CODE`        VARCHAR(50)  NOT NULL UNIQUE,
    `DESCRIPTION` VARCHAR(50)  NOT NULL,
    `MESSAGE`     VARCHAR(255) NOT NULL,
    `CREATE_BY`   VARCHAR(50)  NOT NULL,
    `CREATE_DATE` TIMESTAMP    NOT NULL,
    `UPDATE_BY`   VARCHAR(50)  NOT NULL,
    `UPDATE_DATE` TIMESTAMP    NOT NULL
);
-- ===== /MASTER TABLE =====

-- ===== NORMAL TABLE =====
-- Crawl Web
CREATE TABLE `TBL_N_CRAWL`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME`        VARCHAR(50),
    `URL`         VARCHAR(255),
    `TYPE`        VARCHAR(255),
    `COUNTRY`     VARCHAR(255),
    `SAVE_STATUS` VARCHAR(1),
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL
);
-- Topic
CREATE TABLE `TBL_N_TOPIC`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME`        VARCHAR(50) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL
);

-- Web Item
CREATE TABLE `TBL_N_WEB_ITEM`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME`        VARCHAR(50)  NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    `URL`         VARCHAR(255) NOT NULL,
    `IMAGE_URL`   VARCHAR(255) NOT NULL,
    `CREATE_BY`   VARCHAR(50)  NOT NULL,
    `CREATE_DATE` TIMESTAMP    NOT NULL,
    `UPDATE_BY`   VARCHAR(50)  NOT NULL,
    `UPDATE_DATE` TIMESTAMP    NOT NULL
);

-- Collection
CREATE TABLE `TBL_N_COLLECTION`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `NAME`        VARCHAR(50) NOT NULL,
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL
);

-- ===== /NORMAL TABLE =====

-- ===== JOIN TABLE =====
-- TBL: Topic + Web Item
CREATE TABLE `TBL_J_TOPIC_WEB_ITEM`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `TOPIC_ID`    BIGINT,
    `WEB_ITEM_ID` BIGINT,
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL,
    FOREIGN KEY (TOPIC_ID) REFERENCES TBL_N_TOPIC (ID),
    FOREIGN KEY (WEB_ITEM_ID) REFERENCES TBL_N_WEB_ITEM (ID)
);

-- TBL: User + Web Item
CREATE TABLE `TBL_J_USER_WEB_ITEM`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID`     BIGINT,
    `WEB_ITEM_ID` BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES TBL_M_USER (ID),
    FOREIGN KEY (WEB_ITEM_ID) REFERENCES TBL_N_WEB_ITEM (ID)
);

-- TBL: Collection + Web Item
CREATE TABLE `TBL_J_COLLECTION_WEB_ITEM`
(
    `ID`            BIGINT PRIMARY KEY AUTO_INCREMENT,
    `COLLECTION_ID` BIGINT,
    `WEB_ITEM_ID`   BIGINT,
    `CREATE_BY`     VARCHAR(50) NOT NULL,
    `CREATE_DATE`   TIMESTAMP   NOT NULL,
    `UPDATE_BY`     VARCHAR(50) NOT NULL,
    `UPDATE_DATE`   TIMESTAMP   NOT NULL,
    FOREIGN KEY (COLLECTION_ID) REFERENCES TBL_N_COLLECTION (ID),
    FOREIGN KEY (WEB_ITEM_ID) REFERENCES TBL_N_WEB_ITEM (ID)
);

-- TBL: User + Topic
CREATE TABLE `TBL_J_USER_TOPIC`
(
    `ID`          BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID`     BIGINT,
    `TOPIC_ID`    BIGINT,
    `CREATE_BY`   VARCHAR(50) NOT NULL,
    `CREATE_DATE` TIMESTAMP   NOT NULL,
    `UPDATE_BY`   VARCHAR(50) NOT NULL,
    `UPDATE_DATE` TIMESTAMP   NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TBL_M_USER (ID),
    FOREIGN KEY (TOPIC_ID) REFERENCES TBL_N_TOPIC (ID)
);

-- TBL: User + Collection
CREATE TABLE `TBL_J_USER_COLLECTION`
(
    `ID`            BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID`       BIGINT,
    `COLLECTION_ID` BIGINT,
    `CREATE_BY`     VARCHAR(50) NOT NULL,
    `CREATE_DATE`   TIMESTAMP   NOT NULL,
    `UPDATE_BY`     VARCHAR(50) NOT NULL,
    `UPDATE_DATE`   TIMESTAMP   NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TBL_M_USER (ID),
    FOREIGN KEY (COLLECTION_ID) REFERENCES TBL_N_COLLECTION (ID)
);
-- ===== /JOIN TABLE =====
