INSERT `tbl_m_system_constant` (`CODE`, `DESCRIPTION`, `MESSAGE`, `CREATE_BY`, `CREATE_DATE`, `UPDATE_BY`, `UPDATE_DATE`)
VALUES ('SUCCESS', 'Success', 'Success', 'SYSTEM', CURRENT_TIMESTAMP(), 'SYSTEM', CURRENT_TIMESTAMP());
