insert into `tbl_n_topic` (NAME, DESCRIPTION, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE) value ('Phim', 'Phim', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
insert into `tbl_n_topic` (NAME, DESCRIPTION, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE) value ('Game', 'Game', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
